accepted = [
    "MIT",
    "EUPL-1.2",
    "Apache-2.0",

    "Unicode-3.0",
    "BSD-3-Clause",
    "ISC"
]
targets = [
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu"
]
