name: Security audit
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit-check.yml'
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  security_audit:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true
      - name: Install deps
        run: apk add cargo-audit
      
      - name: Audit
        run: cargo-audit audit
        working-directory: rinb
