on:
  release:
    types: [created]

jobs:
  security_audit:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: apk add cargo-audit
      
      - name: Audit
        run: cargo-audit audit
        working-directory: rinb
      - name: set-matrix
        id: set-matrix
        run: |
            printf 'matrix<<EOF\n%s\nEOF\n' "$MATRIX_JSON" >> $GITHUB_OUTPUT
        env:
          MATRIX_JSON: |
            {
            "target":
              [
                "x86_64-pc-windows-gnu",
                "x86_64-unknown-linux-gnu"
              ]
            }
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs: [security_audit]
    permissions:
     contents: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.security_audit.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            sudo apt-get install mingw-w64
          fi
          
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"  # add freshly installed cargo to $path
          rustup install stable
          rustup target add ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./rinb -> ${{ matrix.target }}"
          prefix-key: "v0-rust-${{ matrix.target }}"
        
      - name: Build executable
        run: |
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            cargo build --target ${{ matrix.target }} --release --locked
          else
            cargo build --target ${{ matrix.target }} --release
          fi
        working-directory: "rinb"
          
      - name: Rename executable to include tag
        id: rename
        run: |
          oldPath="rinb/target/${{ matrix.target }}/release/rinb${{ contains( matrix.target, 'windows') && '.exe' || '' }}"
          mkdir -p out
          newPath="out/rinb-${{matrix.target}}-${{ github.event.release.tag_name }}${{ contains( matrix.target, 'windows') && '.exe' || '' }}"
          cp "$oldPath" "$newPath"

          ${{ contains( matrix.target, 'windows') && '' || 'sudo chmod +x $newPath' }}
      
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: rinb-${{matrix.target}}-${{ github.event.release.tag_name }}
          path: out

  test:
      needs: [security_audit,build]
      strategy:
        fail-fast: false
        matrix: ${{ fromJSON(needs.security_audit.outputs.matrix) }}
      runs-on: ${{ contains( matrix.target, 'windows') && 'windows-latest' || 'ubuntu-latest' }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v5
          with:
            name: rinb-${{matrix.target}}-${{ github.event.release.tag_name }}
            path: out
        - name: Test rinb
          run: |
           out/rinb-${{matrix.target}}-${{ github.event.release.tag_name }}${{ contains( matrix.target, 'windows') && '.exe' || '' }} --config ./rinb.json

  release:
    runs-on: ubuntu-latest
    needs: [security_audit,test]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.security_audit.outputs.matrix) }}
    permissions:
     contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
            name: rinb-${{matrix.target}}-${{ github.event.release.tag_name }}
            path: out
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: out/rinb-${{matrix.target}}-${{ github.event.release.tag_name }}${{ contains( matrix.target, 'windows') && '.exe' || '' }}
          token: ${{ secrets.GITHUB_TOKEN }}